import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "providers/themeProvider/themes";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { GoogleOAuthProvider } from "@react-oauth/google";
import QueryProvider from "providers/queryClient";
import { UserProvider } from "@providers/stateClient/userClient";
import { Toaster } from "@ui/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "PearlPost",
  description: "Generated by PearlPost",
  icons: {
    icon: "logo.webp",
    apple: "logo.webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <QueryProvider>
        <GoogleOAuthProvider clientId="455624080761-2e7vh29o5qldeimm6qn96qaqjhhgk85h.apps.googleusercontent.com">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <UserProvider>
        {children}
        <Toaster position="bottom-right" />
        </UserProvider>
        <ReactQueryDevtools></ReactQueryDevtools>
        </ThemeProvider>
        </GoogleOAuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
